export const flightsConst = [
    { id: 1, airline: 'Sample Airlines', departure: 'New York', arrival: 'Los Angeles', departureTime: '09:00 AM', arrivalTime: '11:30 AM', price: '$150' },
    { id: 2, airline: 'Travel Airways', departure: 'Chicago', arrival: 'Miami', departureTime: '10:30 AM', arrivalTime: '01:00 PM', price: '$180' },
    { id: 3, airline: 'WingStar', departure: 'San Francisco', arrival: 'Seattle', departureTime: '08:00 AM', arrivalTime: '10:30 AM', price: '$130' },
    { id: 4, airline: 'SkyStream', departure: 'Houston', arrival: 'Denver', departureTime: '11:00 AM', arrivalTime: '01:30 PM', price: '$200' },
    { id: 5, airline: 'Pacific Airlines', departure: 'Los Angeles', arrival: 'New York', departureTime: '12:00 PM', arrivalTime: '03:30 PM', price: '$160' },
    { id: 6, airline: 'JetWings', departure: 'Seattle', arrival: 'San Francisco', departureTime: '02:00 PM', arrivalTime: '04:30 PM', price: '$140' },
    { id: 7, airline: 'Global Flights', departure: 'Miami', arrival: 'Chicago', departureTime: '03:30 PM', arrivalTime: '06:00 PM', price: '$190' },
    { id: 8, airline: 'Metro Air', departure: 'Denver', arrival: 'Houston', departureTime: '05:00 PM', arrivalTime: '07:30 PM', price: '$210' },
    { id: 9, airline: 'Sunrise Airlines', departure: 'Los Angeles', arrival: 'Seattle', departureTime: '08:00 AM', arrivalTime: '10:30 AM', price: '$145' },
    { id: 10, airline: 'Breezy Airways', departure: 'San Francisco', arrival: 'Denver', departureTime: '10:00 AM', arrivalTime: '12:30 PM', price: '$175' },
    { id: 11, airline: 'AirLink', departure: 'Chicago', arrival: 'New York', departureTime: '01:30 PM', arrivalTime: '04:00 PM', price: '$165' },
    { id: 12, airline: 'SkyConnect', departure: 'Miami', arrival: 'Houston', departureTime: '04:30 PM', arrivalTime: '07:00 PM', price: '$185' },
    { id: 13, airline: 'Sunset Airlines', departure: 'Houston', arrival: 'Chicago', departureTime: '09:00 AM', arrivalTime: '11:30 AM', price: '$195' },
    { id: 14, airline: 'Oceanic Flights', departure: 'New York', arrival: 'San Francisco', departureTime: '12:30 PM', arrivalTime: '03:00 PM', price: '$170' },
    { id: 15, airline: 'Express Jets', departure: 'Denver', arrival: 'Los Angeles', departureTime: '03:00 PM', arrivalTime: '05:30 PM', price: '$205' },
    { id: 16, airline: 'BlueSky Airways', departure: 'Seattle', arrival: 'Chicago', departureTime: '06:00 PM', arrivalTime: '08:30 PM', price: '$180' },
    { id: 17, airline: 'Swift Air', departure: 'San Francisco', arrival: 'New York', departureTime: '08:30 AM', arrivalTime: '11:00 AM', price: '$155' },
    { id: 18, airline: 'FlyRight Airlines', departure: 'Chicago', arrival: 'Miami', departureTime: '11:00 AM', arrivalTime: '01:30 PM', price: '$190' },
    { id: 19, airline: 'AirWorks', departure: 'New York', arrival: 'Los Angeles', departureTime: '02:30 PM', arrivalTime: '05:00 PM', price: '$175' },
    { id: 20, airline: 'SkyExpress', departure: 'Houston', arrival: 'Denver', departureTime: '05:30 PM', arrivalTime: '08:00 PM', price: '$200' },
    // Add more flight data as needed
  ]

  export const promotionsConst = [
    { id: 1, title: 'Special Student Discount', category: 'Flights', description: 'Get 20% off on all domestic flights. Limited time offer!' },
    { id: 2, title: 'Weekend Getaway Deals', category: 'Packages', description: 'Explore weekend packages starting from $199. Book now!' },
    { id: 3, title: 'Family Vacation Special', category: 'Packages', description: 'Plan your family vacation with our exclusive deals. Kids stay free!' },
    { id: 4, title: 'Last Minute Deals', category: 'Flights', description: 'Grab last-minute flight deals to your favorite destinations.' },
    { id: 5, title: 'Luxury Retreats', category: 'Packages', description: 'Indulge in luxury retreats at unbeatable prices. Book now!' },
    { id: 6, title: 'Adventure Getaways', category: 'Packages', description: 'Experience thrilling adventures with our adventure getaway packages.' },
    { id: 7, title: 'Romantic Escapes', category: 'Packages', description: 'Surprise your loved one with a romantic escape. Book now!' },
    { id: 8, title: 'Business Class Upgrade', category: 'Flights', description: 'Upgrade to business class at a discounted rate.' },
    { id: 9, title: 'Summer Vacation Deals', category: 'Packages', description: 'Plan your summer vacation with our exclusive deals.' },
    { id: 10, title: 'Winter Wonderland Packages', category: 'Packages', description: 'Explore winter wonderland packages for an unforgettable experience.' },
    { id: 11, title: 'Honeymoon Special', category: 'Packages', description: 'Celebrate your honeymoon with our special packages.' },
    { id: 12, title: 'City Breaks', category: 'Packages', description: 'Discover exciting city breaks with our curated packages.' },
    { id: 13, title: 'Beach Vacation Deals', category: 'Packages', description: 'Relax on beautiful beaches with our vacation deals.' },
    { id: 14, title: 'Group Travel Offers', category: 'Flights', description: 'Get exclusive offers for group travel bookings.' },
    { id: 15, title: 'Ski Trip Packages', category: 'Packages', description: 'Plan your ski trip with our amazing packages.' },
    { id: 16, title: 'Cruise Getaways', category: 'Packages', description: 'Embark on a cruise adventure with our getaway packages.' },
    { id: 17, title: 'Historical Tours', category: 'Packages', description: 'Explore history with our guided historical tours.' },
    { id: 18, title: 'Adventure Sports Deals', category: 'Packages', description: 'Enjoy adventure sports with our thrilling deals.' },
    { id: 19, title: 'Food and Wine Tours', category: 'Packages', description: 'Discover food and wine tours for a gastronomic journey.' },
    { id: 20, title: 'Nature Retreats', category: 'Packages', description: 'Connect with nature with our serene retreats.' },
  ]

  export const initialAds = [
    { id: 1, name: 'Summer Travel Deals', description: 'Explore the best summer destinations. Book now!', status: 'Active' },
    { id: 2, name: 'Winter Holiday Packages', description: 'Plan your perfect winter getaway. Limited offers!', status: 'Inactive' },
    { id: 3, name: 'Adventure Escapes', description: 'Experience thrilling adventures. Book your trip now!', status: 'Active' },
    { id: 4, name: 'Luxury Retreats', description: 'Indulge in luxury getaways. Unmatched experiences!', status: 'Active' },
    { id: 5, name: 'Last Minute Deals', description: 'Grab unbeatable last-minute offers. Limited time!', status: 'Active' },
    { id: 6, name: 'Family Vacation Discounts', description: 'Enjoy memorable family vacations. Book today!', status: 'Inactive' },
    { id: 7, name: 'Romantic Getaways', description: 'Discover romantic destinations. Perfect for couples!', status: 'Active' },
    { id: 8, name: 'Cruise Adventures', description: 'Sail away on breathtaking cruises. Don’t miss out!', status: 'Active' },
    { id: 9, name: 'Mountain Retreats', description: 'Find peace in mountain retreats. Exclusive offers!', status: 'Inactive' },
    { id: 10, name: 'City Break Specials', description: 'Explore vibrant cities. Great deals available!', status: 'Active' },
    { id: 11, name: 'Beach Holiday Offers', description: 'Relax on beautiful beaches. Book your dream vacation!', status: 'Active' },
    { id: 12, name: 'Safari Adventures', description: 'Embark on thrilling safaris. Unforgettable experiences!', status: 'Active' },
    { id: 13, name: 'Historical Tours', description: 'Explore historical wonders. Book your journey!', status: 'Active' },
    { id: 14, name: 'Tropical Escapes', description: 'Discover tropical paradises. Special discounts!', status: 'Active' },
    { id: 15, name: 'Gastronomic Journeys', description: 'Savor culinary delights. Exceptional food tours!', status: 'Active' },
    { id: 16, name: 'Festival Get-Togethers', description: 'Celebrate festivals in style. Book your trip!', status: 'Active' },
    { id: 17, name: 'Art and Culture Expeditions', description: 'Immerse in art and culture. Unique experiences!', status: 'Active' },
    { id: 18, name: 'Wellness Retreats', description: 'Rejuvenate in wellness retreats. Relax and unwind!', status: 'Active' },
    { id: 19, name: 'Wildlife Encounters', description: 'Encounter wildlife adventures. Book now!', status: 'Active' },
    { id: 20, name: 'Budget-Friendly Stays', description: 'Find pocket-friendly accommodations. Great deals!', status: 'Active' },
  ];

  export const initialAdds = [
    { id: 1, name: 'Summer Travel Deals', description: 'Explore the best summer destinations. Book now!', status: 'Active' },
    { id: 2, name: 'Winter Holiday Packages', description: 'Plan your perfect winter getaway. Limited offers!', status: 'Inactive' },
    { id: 3, name: 'Adventure Escapes', description: 'Experience thrilling adventures. Book your trip now!', status: 'Active' },
    { id: 4, name: 'Luxury Retreats', description: 'Indulge in luxury getaways. Unmatched experiences!', status: 'Active' },
    { id: 5, name: 'Last Minute Deals', description: 'Grab unbeatable last-minute offers. Limited time!', status: 'Active' },
    { id: 6, name: 'Family Vacation Discounts', description: 'Enjoy memorable family vacations. Book today!', status: 'Inactive' },
    { id: 7, name: 'Romantic Getaways', description: 'Discover romantic destinations. Perfect for couples!', status: 'Active' },
    { id: 8, name: 'Cruise Adventures', description: 'Sail away on breathtaking cruises. Don’t miss out!', status: 'Active' },
    { id: 9, name: 'Mountain Retreats', description: 'Find peace in mountain retreats. Exclusive offers!', status: 'Inactive' },
    { id: 10, name: 'City Break Specials', description: 'Explore vibrant cities. Great deals available!', status: 'Active' },
    { id: 11, name: 'Beach Holiday Offers', description: 'Relax on beautiful beaches. Book your dream vacation!', status: 'Active' },
    { id: 12, name: 'Safari Adventures', description: 'Embark on thrilling safaris. Unforgettable experiences!', status: 'Active' },
    { id: 13, name: 'Historical Tours', description: 'Explore historical wonders. Book your journey!', status: 'Active' },
    { id: 14, name: 'Tropical Escapes', description: 'Discover tropical paradises. Special discounts!', status: 'Active' },
    { id: 15, name: 'Gastronomic Journeys', description: 'Savor culinary delights. Exceptional food tours!', status: 'Active' },
    { id: 16, name: 'Festival Get-Togethers', description: 'Celebrate festivals in style. Book your trip!', status: 'Active' },
    { id: 17, name: 'Art and Culture Expeditions', description: 'Immerse in art and culture. Unique experiences!', status: 'Active' },
    { id: 18, name: 'Wellness Retreats', description: 'Rejuvenate in wellness retreats. Relax and unwind!', status: 'Active' },
    { id: 19, name: 'Wildlife Encounters', description: 'Encounter wildlife adventures. Book now!', status: 'Active' },
    { id: 20, name: 'Budget-Friendly Stays', description: 'Find pocket-friendly accommodations. Great deals!', status: 'Active' },
    // Add more realistic ad data here...
  ];

  export const initialAgents = [
    { id: 1, name: 'Travel Pro Services', description: 'A reputable travel agency with diverse offerings.', status: 'Active' },
    { id: 2, name: 'Global Travel Ventures', description: 'Specializes in luxury travel experiences worldwide.', status: 'Inactive' },
    { id: 3, name: 'Wanderlust Adventures', description: 'Creating unforgettable travel experiences for over a decade.', status: 'Active' },
    { id: 4, name: 'Jet Set Journeys', description: 'Experts in organizing exclusive jet-setting vacations.', status: 'Active' },
    { id: 5, name: 'Voyage Tours and Travels', description: 'Tailored travel solutions for every kind of traveler.', status: 'Active' },
    { id: 6, name: 'Treasure Trails Expeditions', description: 'Specialized in unique and off-the-beaten-path trips.', status: 'Inactive' },
    { id: 7, name: 'Globe Trotting Consultants', description: 'Crafting experiences that broaden horizons.', status: 'Active' },
    { id: 8, name: 'Adventure Awaits Travel Co.', description: 'Bringing the thrill of adventure to every trip.', status: 'Active' },
    { id: 9, name: 'Wise Wanderers Agency', description: 'Helping travelers discover the world with wisdom.', status: 'Inactive' },
    { id: 10, name: 'Horizon Explorers', description: 'Expanding horizons through exceptional travel.', status: 'Active' },
    { id: 11, name: 'Boundless Journeys', description: 'Embark on journeys that know no boundaries.', status: 'Active' },
    { id: 12, name: 'Nomad Navigator', description: 'Navigating nomads to new and exciting destinations.', status: 'Active' },
    { id: 13, name: 'Pioneer Planners', description: 'Pioneering travel experiences beyond the ordinary.', status: 'Active' },
    { id: 14, name: 'Epic Escapades Agency', description: 'Epic journeys for those seeking extraordinary experiences.', status: 'Active' },
    { id: 15, name: 'Vivid Vistas Travel Group', description: 'Creating vivid memories in breathtaking vistas.', status: 'Active' },
    { id: 16, name: 'Dream Destinations Tours', description: 'Making dreams of travel destinations come true.', status: 'Active' },
    { id: 17, name: 'Odyssey Outfitters', description: 'Outfitting odysseys that leave lasting impressions.', status: 'Active' },
    { id: 18, name: 'Journey Joy Consultants', description: 'Bringing joy to every step of the travel journey.', status: 'Active' },
    { id: 19, name: 'Voyager Ventures', description: 'Venturing voyages for all types of explorers.', status: 'Active' },
    { id: 20, name: 'Trailblazer Trips', description: 'Blazing trails in travel experiences around the world.', status: 'Active' },
    // Add more realistic agent data here...
  ];
  
  
  
  